# Internationalization module
OPTIONS = {
    "es": {
        "username": "Usuario",
        "password": "Contraseña",
        "empty_fields": "*Campos vacios",
        "login": "Iniciar sesión",
        "question": "¿No tienes una cuenta?",
        "invalid_account": "*Usuario o contraseña incorrectos.",
        "account": "Crea una",
        "change_language": "Change language",
        "invalid_password": "*Las contraseñas no coinciden",
        "invalid_username": "*Nombre de usuario ya existente",
        "invalid_email": "*Correo electrónico ya existente",
        "name": "Nombre",
        "email": "Correo electrónico",
        "conf_password": "Confirmar contraseña",
        "register": "Registrar",
        "score": "Ver puntuación",
        "logout": "Cerrar Sesión",
        "send": "Enviar",
        "exit": "Salir",
        "friends": "Amigos",
        "randomize": "Reacomodar",
        "leave": "Abandonar partida",
        "start": "Iniciar juego",
        "player": "Tu flota",
        "enemy": "Enemigo",
    },
    "en": {
        "username": "User",
        "password": "Password",
        "empty_fields": "*Empty fields",
        "login": "Login",
        "question": "Don't you have an account?",
        "invalid_account": "*Incorrect user or password",
        "account": "Create one",
        "change_language": "Cambiar idioma",
        "invalid_password": "*The passwords are not the same",
        "invalid_username": "*User name already existent",
        "invalid_email": "*E-mail already existent",
        "name": "Name",
        "email": "E-mail",
        "conf_password": "Confirm password",
        "register": "Register",
        "score": "Score",
        "logout": "Logout",
        "send": "Send",
        "exit": "Exit",
        "friends": "Friends",
        "randomize": "Randomize",
        "leave": "Leave match",
        "start": "Start",
        "player": "Your ships",
        "enemy": "Enemy",
    }
}
